chore: update flake.lock
In its previous version, entering the dev shell and attempting `cargo check` would result in this error:

error: failed to parse manifest at `/home/alice/.cargo/registry/src/index.crates.io-6f17d22bba15001f/resource_list_proc_macro-0.6.0/Cargo.toml`

Caused by:
  feature `edition2024` is required

  The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.83.0 (5ffbef321 2024-10-29)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024 for more information about the status of this feature.